# Generated by Django 2.1.3 on 2018-11-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishname', models.TextField(blank=True, db_column='DishName', null=True)),
                ('price', models.FloatField(blank=True, db_column='Price', null=True)),
                ('restaurant', models.TextField(blank=True, db_column='Restaurant', null=True)),
                ('foodurl', models.URLField(blank=True, db_column='foodURL', null=True)),
                ('imageurl', models.URLField(blank=True, db_column='imageURL', null=True)),
                ('deliveryapp', models.TextField(blank=True, db_column='DeliveryApp', null=True)),
            ],
            options={
                'db_table': 'PriceData',
            },
        ),
    ]
