# Generated by Django 2.1.3 on 2018-11-09 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricedata',
            options={'ordering': ['price']},
        ),
    ]
